name: ci

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 第一步：检出代码
      - name: Checkout
        uses: actions/checkout@v3

      # 第二步：设置 Node.js 环境
      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # 第三步：缓存 Node 模块
      - name: Cache node modules
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: ./node_modules
          key: ${{ runner.os }}-build-cache-node-modules-${{ hashFiles('**/package.json') }}
          restore-keys: |
            cache-node-modules-

      # 第四步：安装依赖并运行 CI 脚本
      - name: Run ci
        run: |
          pnpm install
          pnpm run ci
